config/routes.rb
Tuner::Application.routes.draw do
 root :to => 'home#index'



get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

post "/song/purchase/" => 'users#purchase', :as => 'purchase'

resources :users

resources :genres
resources :artists
resources :songs
resources :mixtapes


end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id    :integer          not null, primary key
#  name  :string(255)
#  image :string(255)
#

class Artist <ActiveRecord::Base
attr_accessible :name, :image, :album_ids, :song_ids
has_many :songs
has_many :albums, :through => :songs
validates :name ,:uniqueness => true, :presence => true

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :check_if_admin, :except => [:index]

def index
  @artists = Artist.order(:name)
end
def show
  @artist = Artist.find(params[:id])
end

def new
  @artist = Artist.new()
end
def create
  @artist = Artist.new(params[:artist])
  @artist.save ? redirect_to(artists_path) : render(:new)
end

def edit
  @artist = Artist.find(params[:id])
  render :new
end

def update
  Artist.find(params[:id]).update_attributes(params[:artist]) ? redirect_to(artists_path) : render(:new)
end

def destroy
  Artist.find(params[:id]).delete
  redirect_to artists_path
end


end

app/views/artists/index.html.haml
.six.columns.centered
  %h1
    Artists
    =link_to("Add Artist", new_artist_path,:class=>'button') if is_admin
  %table
    -@artists.each do |artist|
      %tr
        %td
          =link_to(artist.name,artist)
        %td
          =image_tag(artist.image)
        -if is_admin
          %td
            =link_to("Edit", edit_artist_path(artist.id), :class=>'button')
          %td
            =link_to("Delete", artist,:method=>"delete", :class=>'button alert')

app/views/artists/new.html.haml
.eight.columns.centered
  = render(:partial => 'shared/errors' , :locals => {:object => @artist})
  =form_for @artist do |a|
    =a.label :name
    =a.text_field :name ,:autofocus => true
    =a.label :image
    =a.text_field :image
    %ul
      -Album.all.each do |album|
        =check_box_tag('artist[album_ids][]' , album.id, album.in?(@artist.albums))
        =album.name
    =a.submit nil, :class => 'button radius'

app/views/artists/show.html.haml
.six.columns.centered
  %h2
    =@artist.name
    %br
    =image_tag(@artist.image,:class=>'artistimage')