config/routes.rb
Tuner::Application.routes.draw do
 root :to => 'home#index'



get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

post "/song/purchase/" => 'users#purchase', :as => 'purchase'

resources :users

resources :genres
resources :artists
resources :songs
resources :mixtapes


end

app/models/mixtape.rb
# == Schema Information
#
# Table name: mixtapes
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Mixtape < ActiveRecord::Base
  attr_accessible :name, :user_id, :song_ids
  validates :name, :length => { :minimum => 2}
  belongs_to :user
  has_and_belongs_to_many :songs
end

app/controllers/mixtapes_controller.rb
class MixtapesController <ApplicationController



def index
  @mixtapes = @auth.mixtapes
end

def show
  mixtape = Mixtape.find(params[:id])
  if @auth.mixtapes.include?(mixtape)
      @mixtape = mixtape
      render :show
  else
    redirect_to(mixtapes_path)
  end
end

def new
  is_auth ? @mixtape = Mixtape.new() : redirect_to(login_path)
end

def create
  @mixtape = Mixtape.new(params[:mixtape])
  if @mixtape.save
      add_mixtape_to_user(@mixtape)
      redirect_to(@mixtape)
  else
      render :new
  end
end


def update
  mt = Mixtape.find(params[:id])
  if mt.update_attributes(params[:mixtape])
    redirect_to mixtape_path(mt.id)
  else
    render :new
  end

end
def edit
  @mixtape = Mixtape.find(params[:id])
  render :new
end

def destroy
    Mixtape.find(params[:id]).delete
    redirect_to mixtapes_path
end


end

app/views/mixtapes/index.html.haml
.row
  .nine.columns.centered
    %h3 Your Mixtapes
    .create
      -if is_auth
        =link_to("Add Mixtapes", new_mixtape_path,:class=>'button')
    %table.centered
      -@auth.mixtapes.each do |mixtape|
        %tr
          %td
            =link_to(mixtape.name,mixtape)
          -if is_admin
            %td
              =link_to("Edit", edit_mixtape_path(mixtape.id),:class=>'button')
            %td
              =link_to("Delete", mixtape, :method =>'delete', :confirm => 'Are you sure?' ,:class=>'alert button' )

app/views/mixtapes/new.html.haml
.row
  .six.columns.centered
    %h3
      Mixtape
    = render(:partial => 'shared/errors' ,:locals => {:object => @mixtape})
    =form_for @mixtape do |a|
      =a.label :name
      =a.text_field :name, :autofocus => true
      %ul
        -usersongs.each do |song|
          %li
            =check_box_tag('mixtape[song_ids][]' , song.id, song.in?(@mixtape.songs))
            =song.name
      =a.submit nil, :class=>'button radius'

app/views/mixtapes/show.html.haml
.nine.columns.centered
  %h2
    =@mixtape.name
  -if @mixtape.name != "All Songs"
    %h4
      =button_to("Delete", @mixtape, :method =>'delete', :confirm => 'Are you sure?' ,:class=>'alert button radius ' )
  .edit
    %h4
      =link_to("Edit", edit_mixtape_path(@mixtape.id),:class=>'button')
  .addsongs
    =link_to("Add Songs",songs_path,:class=>'button' )
  %hr
    %ul
      -@mixtape.songs.each do |song|
        %li
          -if !song.name.nil?
            =link_to(song.name,song)
          -if !song.artist.nil?
            by
            =link_to(song.artist.name,song.artist)