config/routes.rb
Tuner::Application.routes.draw do
 root :to => 'home#index'



get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

post "/song/purchase/" => 'users#purchase', :as => 'purchase'

resources :users

resources :genres
resources :artists
resources :songs
resources :mixtapes


end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  artist_id  :integer
#  album_id   :integer
#  image      :string(255)
#  filename   :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  price      :decimal(, )      default(1.0)
#

class Song < ActiveRecord::Base
attr_accessible :name, :image, :filename,:genre_ids,:artist_ids,:album_ids,:price,:mixtape_ids

      belongs_to :album
      belongs_to :artist
      has_and_belongs_to_many :mixtapes
      has_and_belongs_to_many :genres

      def player
        filepath = nil
          if !self.filename.nil? && !self.filename.split("watch?v=")[1].nil?
           filepath = self.filename.split("watch?v=")[1]
           stringone = '<object type="application/x-shockwave-flash" width="150" height="25" data="https://www.youtube-nocookie.com/v/'
           stringone +=filepath
           stringone += "?version=2&theme=dark\"><param name='movie' value='https://www.youtube-nocookie.com/v/"
           stringone +=filepath
           stringone += "?version=2&theme=dark' /><param name='wmode' value='transparent' /></object>"
         else
          stringone = "Incorrect Filepath Provided. Please Edit"
         end
           stringone
      end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
before_filter :check_if_admin, :except => [:index,:show]

#No check for admin
def index
 @songs = Song.all(:order => :name)
end
def show
  @song = Song.find(params[:id])
  @client ||= YouTubeIt::Client.new(:dev_key => "AI39si4QPB-NMrFRP_VsRYhKN2MTh0Qm0csilcEMd0YoPGZ5bWWZ0_Ibw_G8VjHhgFHzDvg0MGKYL2Tp_BlwVTV20KCpPcekfw")

    q = @client.videos_by(:query => "penguin")
    options={:class => 'video-player', :id => 'my-video', :width => '1000', :height => '250', :frameborder => '',}
    @html = q.videos.first.embed_html5(options)

end

#Freshies (admin only)
def new
  @song = Song.new()
end
def create
  @song = Song.new(params[:song])
  @song.save ? redirect_to(songs_path) : render(:new)
end

#Oldies trick (admin only)
def edit
  @song = Song.find(params[:id])
  render :new
end
def update
Song.find(params[:id]).update_attributes(params[:song]) ? redirect_to(songs_path) : render(:new)
end

def destroy
  Song.find(params[:id]).delete ? redirect_to(songs_path) : []
end


end

app/views/songs/index.html.haml
.row
  .six.columns.centered
    %h2
      All Songs
      -if is_admin
        =link_to("New Song",new_song_path,:class=>'button')
    %table
      -@songs.each do |song|
        %tr
          -if is_admin
            %td
              =link_to("Edit",edit_song_path(song.id),:class=>'button')
            %td
              =link_to("Delete", song , :method =>'delete', :confirm => 'Are you sure?',:class=>'button alert')
          %td
            -song.name ="Blank" if song.name.nil?
            =link_to(song.name,song)
          %td
            -if !song.artist.nil?
              =link_to(song.artist.name,song.artist)
          %td
            != sbutton(song)

app/views/songs/new.html.haml
.row
  .six.columns.centered
    %h3
      Song
    = render(:partial => 'shared/errors' ,:locals => {:object => @song})
    =form_for @song do |a|
      =a.label :name
      =a.text_field :name, :autofocus => true
      =a.label :image
      =a.text_field :image
      =a.label :filename
      =a.text_field :filename

      / =a.text_field(:album_ids, :type=>'hidden',:value=>"0")


      -Genre.all.each do |genre|
        =check_box_tag('song[genre_ids][]' , genre.id, genre.in?(@song.genres.to_a))
        =genre.name
      %br
      %br


      / -Artist.all.each do |artist|
      /   =radio_button('song[]' , artist.id, @song.artist.nil?)
      /   =artist.name

      .submit
      =a.submit nil, :class=>'button radius'

app/views/songs/show.html.haml
.five.columns.centered
  %h2
    =@song.name
  %h4
    =link_to("Edit",edit_song_path(@song.id),:class=>'button') if is_admin
    =link_to("Songs",songs_path,:class=>'button')if is_admin
  .genrelist.songspace
    %hr
    Genres:
    -@song.genres.each do |genre|
      =link_to(genre.name,genre)
      %br
    -if !@song.artist.nil?
      .artist.songspace
        Artist:
        =link_to(@song.artist.name,@song.artist)
  .playbutton.songspace
    %hr
    /!= @song.player
  - if (!@auth.nil?)
    - if (@auth.balance > @song.price)
      Price:
      %a.button.success.radius{ :"data-reveal-id" =>"purchasemod"}
        =sbutton(@song)

#purchasemod.reveal-modal.expand.large
  %h2
    Purchase:
    =@song.name
    %h5
      Price:
      =@song.price
      =form_for @song, :url=> purchase_path, :method => :post do |s|
        =hidden_field_tag(:id, @song.id)
        -@auth.mixtapes.each do |mixtape|
          -if mixtape.name == "All Songs"
            /Display None (auto added to All songs)
          -else
            =check_box_tag('song[mixtape_ids][]' , mixtape.id, mixtape.in?(@song.mixtapes.to_a))
            %h6= mixtape.name
        = s.submit("Buy!",:class=>'button radius success')