config/routes.rb
Tuner::Application.routes.draw do
 root :to => 'home#index'



get '/login' => 'session#new'
post '/login' => 'session#create'
delete '/login' => 'session#destroy'

post "/song/purchase/" => 'users#purchase', :as => 'purchase'

resources :users

resources :genres
resources :artists
resources :songs
resources :mixtapes


end

app/views/layouts/_footer.html.erb
  <footer class="row">
    <div class="twelve columns">
      <hr />
      <div class="row">
        <div class="six columns">
          <p>&copy; Copyright no one at all. Go to town.</p>
        </div>
        <div class="six columns">
          <ul class="link-list right">
            <li><a href="http://www.twitter.com/h55nick">Twitter</a></li>
            <li><a href="#">Section 2</a></li>
            <li><a href="#">Section 3</a></li>
            <li><a href="#">Section 4</a></li>
            <li><a href="#">Section 5</a></li>
            <li><a href="#">Section 6</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<div class="row">
  <div class="six columns">
    <div class="panel">
      <%=image_tag("http://www.daviddisalvo.org/storage/Baby-music.jpg?",:class=>'baby' )%>
        <span class='header'>Tuner<span>
    </div>
    </div>


      <!-- Call to Intellinav -->
<div class='six columns'>
        <%== intellinav %>
        <div class='row'>
          <div class='twelve columns'>
              <ul class='nav-bar right' id='nonintel'>
                <%if is_auth && @auth.mixtapes.count > 0%>
                <li class='has-flyout' >
                  <%= link_to("Mixtapes", mixtapes_path )%>
                  <a href='#' class='flyout-toggle'><span> </span></a>
                  <ul class='flyout'>
                      <%  @auth.mixtapes.each do |mtape|%>
                          <li><%=link_to(mtape.name, mtape )%></li>
                      <%end%>
                        <li><%=link_to("Add Mixtape", new_mixtape_path,:id=>"addmixdropdown")%></li>
            </ul>
            <%end%>
        <li class='has-flyout'>
            <a href='#'>Browse</a>
            <a href='#' class='flyout-toggle'><span> </span></a>
        <ul class='flyout'>
          <li><%=link_to("Artist", artists_path)%></li>
          <li><%=link_to("Genres", genres_path)%></li>
          <li><%=link_to("Songs", songs_path)%></li>
          <li><%=link_to("Mixtapes", mixtapes_path) if is_auth %></li>
        </ul>
        <li>
            <%=link_to('Show Users', users_path,:class=>"") if !@auth.nil? && @auth.is_admin %>
        </li>
        </ul>
      </div>
      </div>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Tuner" %></title>

	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>

	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Header and Nav -->
<%= render :partial => "layouts/nav" %>
  <!-- End Header and Nav -->

<% if flash[:notice].present? %>
<div class='row'>
  <div class='six columns alert-box alert centered'>
    <%=flash[:notice]%>
    <a href="" class="close">&times;</a>
  </div>
</div>
<%end%>



<div class='row'>
  <div class='twelve columns'>
    <%= yield %>
  </div>
</div>

    <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="three columns pull-six">
      <div class="panel">
        <h5>
          <%if !@auth.nil? %>
            <%= image_tag(@auth.image) %>
          <%end%>
        </h5>

        <dl class="vertical tabs">
          <dd><a href="#">Section 1</a></dd>
          <dd><a href="#">Section 2</a></dd>
          <dd><a href="#">Section 3</a></dd>
          <dd><a href="#">Section 4</a></dd>
          <dd><a href="#">Section 5</a></dd>
          <dd><a href="#">Section 6</a></dd>
        </dl>

      </div>
    </div>

  <!-- Footer -->
<%= render :partial => "layouts/footer" %>

</body>
</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title><%= content_for?(:title) ? yield(:title) : "Tuner" %></title>

	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>

	<!-- Included JS Files  -->
	<%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Header and Nav -->
<%= render :partial => "layouts/nav" %>
  <!-- End Header and Nav -->


  <div class="row">

    <!-- Main Feed -->
    <!-- This has been source ordered to come first in the markup (and on small devices) but to be to the right of the nav on larger screens -->
    <div class="six columns push-three">


    	  <%= yield %>



<%if is_auth %>
      <!-- Feed Entry -->
      <div class="row">
        <div class="two columns mobile-one"><img src="http://placehold.it/80x80&text=[img]" /></div>
        <div class="ten columns">
          <p><strong>Some Person said:</strong> Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.</p>
          <ul class="link-list">
            <li><a href="">Reply</a></li>
            <li><a href="">Share</a></li>
          </ul>


          <h6>2 Comments</h6>
          <div class="row">
            <div class="two columns mobile-one"><img src="http://placehold.it/50x50&text=[img]" /></div>
            <div class="ten columns"><p><%= yield %>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p></div>
          </div>
          <div class="row">
            <div class="two columns mobile-one"><img src="http://placehold.it/50x50&text=[img]" /></div>
            <div class="ten columns"><p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p></div>
          </div>
        </div>
      </div>

      <!-- End Feed Entry -->

      <hr />

      <!-- Feed Entry -->
      <div class="row">
        <div class="two columns mobile-one"><img src="http://placehold.it/80x80&text=[img]" /></div>
        <div class="ten columns">
          <p><strong>Some Person said:</strong> Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.</p>
          <ul class="link-list">
            <li><a href="">Reply</a></li>
            <li><a href="">Share</a></li>
          </ul>
        </div>
      </div>
      <!-- End Feed Entry -->

      <hr />

      <!-- Feed Entry -->
      <div class="row">
        <div class="two columns mobile-one"><img src="http://placehold.it/80x80&text=[img]" /></div>
        <div class="ten columns">
          <p><strong>Some Person said:</strong> Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong.</p>
          <ul class="link-list">
            <li><a href="">Reply</a></li>
            <li><a href="">Share</a></li>
          </ul>


          <h6>2 Comments</h6>
          <div class="row">
            <div class="two columns mobile-one"><img src="http://placehold.it/50x50&text=[img]" /></div>
            <div class="ten columns"><p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit</p></div>
          </div>
        </div>
      </div>
      <!-- End Feed Entry -->

    </div>


    <!-- Nav Sidebar -->
    <!-- This is source ordered to be pulled to the left on larger screens -->
    <div class="three columns pull-six">
      <div class="panel">
        <h5>
          <%if !@auth.nil? %>
            <%= image_tag(@auth.image) %>
          <%end%>
        </h5>

        <dl class="vertical tabs">
          <dd><a href="#">Playlist 1</a></dd>
          <dd><a href="#">Playlist 2</a></dd>
          <dd><a href="#">Playlist 3</a></dd>
          <dd><a href="#">Playlist 4</a></dd>
        </dl>

      </div>
    </div>

    <%else%>

<div class='row'>
  <div class='column nine'>
            <div id='nolog' >
            <%=link_to("sign in",login_path,:class=>'button success') %>

            <%=link_to('sign up',new_user_path,:class=>'button success') %>
          </div>

  </div>




    <!-- Right Sidebar -->
    <!-- On small devices this column is hidden -->
    <aside class="three columns hide-for-small">
      <p><img src="http://placehold.it/300x440&text=[ad]" /></p>
      <p><img src="http://placehold.it/300x440&text=[ad]" /></p>
    </aside>

  </div>
</div>
<%end%>


  <!-- Footer -->
<%= render :partial => "layouts/footer" %>

</body>
</html>